In [197]:
import pandas as pd
import numpy as np

In [198]:
print("lets python")

lets python

* In the vg-stats notebook answer the following questions/do the following tasks. Note that the numbers quoted for sales are in the millions, and apply only for those games with over 10,000 sales.:
* Which company is the most common video game publisher?
* What’s the most common platform?
* What about the most common genre?
* What are the top 20 highest grossing games?
* For North American video game sales, what’s the median?
* Provide a secondary output showing ten games surrounding the median sales output
* assume that games with same median value are sorted in descending order
* For the top-selling game of all time, how many standard deviations above/below the mean are its sales for North America?
* The Nintendo Wii seems to have outdone itself with games. How does its average number of sales compare with all of the other platforms?
* Come up with 3 more questions that can be answered with this data set.

In [199]:
df = pd.read_csv('./vgsales.csv')
df

,Rank,Name,Platform,Year,Genre,Publisher,NA_Sales,EU_Sales,JP_Sales,Other_Sales,Global_Sales
0,1,Wii Sports,Wii,2006.0,Sports,Nintendo,41.49,29.02,3.77,8.46,82.74
1,2,Super Mario Bros.,NES,1985.0,Platform,Nintendo,29.08,3.58,6.81,0.77,40.24
2,3,Mario Kart Wii,Wii,2008.0,Racing,Nintendo,15.85,12.88,3.79,3.31,35.82
3,4,Wii Sports Resort,Wii,2009.0,Sports,Nintendo,15.75,11.01,3.28,2.96,33.00
4,5,Pokemon Red/Pokemon Blue,GB,1996.0,Role-Playing,Nintendo,11.27,8.89,10.22,1.00,31.37
...,...,...,...,...,...,...,...,...,...,...,...
16593,16596,Woody Woodpecker in Crazy Castle 5,GBA,2002.0,Platform,Kemco,0.01,0.00,0.00,0.00,0.01
16594,16597,Men in Black II: Alien Escape,GC,2003.0,Shooter,Infogrames,0.01,0.00,0.00,0.00,0.01
16595,16598,SCORE International Baja 1000: The Official Game,PS2,2008.0,Racing,Activision,0.00,0.00,0.00,0.00,0.01
16596,16599,Know How 2,DS,2010.0,Puzzle,7G//AMES,0.00,0.01,0.00,0.00,0.01
16597,16600,Spirits & Spells,GBA,2003.0,Platform,Wanadoo,0.01,0.00,0.00,0.00,0.01

In [200]:
df = pd.read_csv('./vgsales.csv')
df
df['Publisher'].value_counts().idxmax()

'Electronic Arts'

In [201]:
df['Platform'].value_counts().idxmax()

'DS'

In [202]:
df['Genre'].value_counts().idxmax()

'Action'

In [203]:
the_shiznit = df.nlargest(20, ['Global_Sales'])

In [204]:
sorted_rows = df.sort_values("Global_Sales", ascending=False)
na_sales_median = df.sort_values('NA_Sales', ascending=False)
mid_point = len(na_sales_median)//2+1

In [205]:
na_sales_median.iloc[mid_point]
na_sales_median.iloc[mid_point - 5:  mid_point + 5]

,Rank,Name,Platform,Year,Genre,Publisher,NA_Sales,EU_Sales,JP_Sales,Other_Sales,Global_Sales
9569,9571,Batman: Arkham Knight,PC,2015.0,Action,Warner Bros. Interactive Entertainment,0.08,0.03,0.00,0.01,0.13
8550,8552,Wakeboarding Unleashed Featuring Shaun Murray,PS2,2003.0,Sports,Activision,0.08,0.06,0.00,0.02,0.16
10799,10801,Mind Quiz,PSP,2006.0,Action,Ubisoft,0.08,0.01,0.00,0.01,0.10
9197,9199,The Walking Dead: Season Two,XOne,2014.0,Adventure,Telltale Games,0.08,0.05,0.00,0.01,0.14
9192,9194,Dino Crisis 3,XB,2003.0,Action,Capcom,0.08,0.03,0.03,0.00,0.14
10181,10183,Smash Court Tennis 3,X360,2007.0,Sports,Atari,0.08,0.02,0.00,0.01,0.11
8802,8804,Disney's The Lion King: Simba's Mighty Adventure,PS,2000.0,Action,Activision,0.08,0.06,0.00,0.01,0.15
8724,8726,Driven,PS2,2001.0,Racing,BAM! Entertainment,0.08,0.06,0.00,0.02,0.15
10793,10795,Glory Days 2,DS,2007.0,Strategy,Ghostlight,0.08,0.00,0.00,0.01,0.10
10298,10300,National Geographic Challenge!,Wii,2011.0,Misc,Black Bean Games,0.08,0.02,0.00,0.01,0.11

In [222]:
sorted_rows = df.sort_values("Global_Sales", ascending=False)
top_game = df.loc[:0]
mean_sales = np.mean(top_game)
mean_sales
deviation = np.std(sorted_rows)
deviation = deviation["Global_Sales"]
deviation

1.5549810910296606

In [224]:
wii_data = df[df['Platform'] == 'Wii']
wii_data

,Rank,Name,Platform,Year,Genre,Publisher,NA_Sales,EU_Sales,JP_Sales,Other_Sales,Global_Sales
0,1,Wii Sports,Wii,2006.0,Sports,Nintendo,41.49,29.02,3.77,8.46,82.74
2,3,Mario Kart Wii,Wii,2008.0,Racing,Nintendo,15.85,12.88,3.79,3.31,35.82
3,4,Wii Sports Resort,Wii,2009.0,Sports,Nintendo,15.75,11.01,3.28,2.96,33.00
7,8,Wii Play,Wii,2006.0,Misc,Nintendo,14.03,9.20,2.93,2.85,29.02
8,9,New Super Mario Bros. Wii,Wii,2009.0,Platform,Nintendo,14.59,7.06,4.70,2.26,28.62
...,...,...,...,...,...,...,...,...,...,...,...
16517,16520,Teenage Mutant Ninja Turtles,Wii,2007.0,Action,Konami Digital Entertainment,0.00,0.01,0.00,0.00,0.01
16552,16555,Mahou Sensei Negima!? Neo-Pactio Fight!!,Wii,2007.0,Fighting,Marvelous Interactive,0.00,0.00,0.01,0.00,0.01
16573,16576,Mini Desktop Racing,Wii,2007.0,Racing,Popcorn Arcade,0.01,0.00,0.00,0.00,0.01
16574,16577,Yattaman Wii: BikkuriDokkiri Machine de Mou Ra...,Wii,2008.0,Racing,Takara Tomy,0.00,0.00,0.01,0.00,0.01
16581,16584,Fit & Fun,Wii,2011.0,Sports,Unknown,0.00,0.01,0.00,0.00,0.01